[package]
name = "deepseek_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "stream"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
atty = "0.2"
futures = "0.3"
bytes = "1.0"
chrono = "0.4"
rust-i18n = "3.1.5"

[package.metadata.i18n]
# The available locales for your application, default: ["en"].
available-locales = ["zh-CN","en"]

# The default locale, default: "en".
default-locale = "zh-CN"

# Path for your translations YAML file, default: "locales".
# This config for let `cargo i18n` command line tool know where to find your translations.
# You must keep this path same as the one you pass to method `rust_i18n::i18n!`.
load-path = "locales"
